# Generated by Django 3.2.5 on 2022-04-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_stripecustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
